version: "3"
services:
  reverseproxy:
      image: pradeeppaidock/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: pradeeppaidock/udagram-users-api
    environment:
      POSTGRES_USERNAME: hidden
      POSTGRES_PASSWORD: hidden
      POSTGRES_DB: hidden 
      POSTGRES_HOST: hidden
      AWS_REGION: hidden
      AWS_PROFILE: default 
      AWS_BUCKET: hidden
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  backend-feed:
    image: hidden
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: hidden
      POSTGRES_PASSWORD: hidden
      POSTGRES_DB: hidden 
      POSTGRES_HOST: hidden
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_BUCKET: hidden
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  frontend:
    image: hidden
    ports:
      - "8100:80"
