version: "3"
services:
  reverseproxy:
      image: pradeeppaidock/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: pradeeppaidock/udagram-users-api
    environment:
      POSTGRES_USERNAME: udagrampaidb
      POSTGRES_PASSWORD: Clijsters32
      POSTGRES_DB: udagrampaidb 
      POSTGRES_HOST: udagrampaidb.cb7zphooz3xh.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_BUCKET: udagrampaidev
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  backend-feed:
    image: pradeeppaidock/udagram-feed-api
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: udagrampaidb
      POSTGRES_PASSWORD: Clijsters32
      POSTGRES_DB: udagrampaidb 
      POSTGRES_HOST: udagrampaidb.cb7zphooz3xh.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default 
      AWS_BUCKET: udagrampaidev
      JWT_SECRET: hello
      URL: "http://localhost:8100"
  frontend:
    image: pradeeppaidock/udagram-frontend
    ports:
      - "8100:80"
